name: Publish Image

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os-arch: [linux/amd64, linux/arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/docker-texlive-${{ matrix.lang }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and Push Ubuntu Image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ matrix.os-arch }}
          file: Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
