name: Publish Image

on:
  push:
  pull_request:

env:
  IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/docker-texlive:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and Push Ubuntu Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          repository: ${{ github.repository }}
          tags: ${IMAGE_TAG}